07-19-orientation-django-exercise/history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

07-19-orientation-django-exercise/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls')),
]

07-19-orientation-django-exercise/history/models.py
from django.db import models

class Artist(models.Model):
  name = models.TextField(default="")
  birth_date = models.TextField(default="")
  biggest_hit = models.TextField(default="")

class Song(models.Model):
  title = models.TextField(default="")
  album = models.TextField(default="")
  artist = models.ForeignKey(Artist, on_delete=models.CASCADE, )

07-19-orientation-django-exercise/history/views.py
from django.shortcuts import render, get_object_or_404
from history.models import Artist, Song

def artists(request):
  artist_list = Artist.objects.all()
  print("artist list??", artist_list)
  context = {"artists": artist_list}
  return render(request, 'history/artists.html', context) # Is request needed in order to complete the req/res cycle?

def new_artist(request):
  print(request.POST)
  # Create a new record using the model's constructor.
  # Artist.create(request.POST)

def detail(request, artist_id):
  print("this is a detail request")
  artist = get_object_or_404(Artist, pk=artist_id)
  # Can get related songs a couple of ways:
  # songs = Song.objects.filter(artist_id=artist_id)
  # or...
  songs = artist.song_set.all()
  return render(request, 'history/detail.html', {"artist": artist, "songs": songs})

07-19-orientation-django-exercise/history/templates/history/artists.html
<h1>Howdy. These Are Made Up Singers. </h1>

<ul>
  {% for artist in artists %}
    <li>
      <a href="{% url 'history:detail' artist.id %}">{{artist.name}}</a>
    </li>
  {% endfor %}
</ul>

07-19-orientation-django-exercise/history/templates/history/detail.html
<h1>This is an Artist and some Songs They Recorded</h1>

<h2>{{artist.name}}</h2>
<h3>Born on {{artist.birth_date}}</h3>
<h3>Most Famous Song: {{artist.biggest_hit}}</h3>

<h2>Some other songs {{artist.name}} is known for</h2>
<ul>
  {% for song in songs %}
    <li>
      {{song.title}}, from the album {{song.album}}
    </li>
  {% endfor %}
</ul>